# Generated by Django 5.0.3 on 2024-05-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='term',
            field=models.CharField(max_length=10),
        ),
    ]
